name: Smoke Tests

on:
  push:
    branches: [ main, master, clean_up ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    container:
      image: archlinux:latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup system
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm \
          base-devel git curl fish sudo \
          which openssl
        
        # Configure sudo
        echo 'root ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        useradd -m -G wheel testuser
        echo 'testuser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        
        # Make scripts executable
        chmod +x *.fish
      
    - name: Test htop installation
      run: |
        echo "Testing htop installation..."
        cd /__w/CachyOS-Setup
        yes n | timeout 60 ./htop.fish || echo "htop test completed (may have prompted)"
        
        # Verify it's available
        pacman -Q htop && echo "✓ htop installed" || echo "⚠ htop not found"
      
    - name: Test netcat installation
      run: |
        echo "Testing netcat installation..."
        cd /__w/CachyOS-Setup
        yes n | timeout 60 ./netcat.fish || echo "netcat test completed"
        
        # Verify it's available
        pacman -Q gnu-netcat && echo "✓ netcat installed" || echo "⚠ netcat not found"
      
    - name: Test Chromium installation (optional)
      continue-on-error: true
      run: |
        echo "Testing Chromium installation..."
        cd /__w/CachyOS-Setup
        yes n | timeout 180 ./chromium.fish || echo "Chromium test completed"
        
        if pacman -Q chromium 2>/dev/null; then
          echo "✓ Chromium installed"
        else
          echo "⚠ Chromium installation skipped or failed"
        fi
      
    - name: Test VLC installation
      continue-on-error: true
      run: |
        echo "Testing VLC installation..."
        cd /__w/CachyOS-Setup
        yes n | timeout 180 ./vlc.fish || echo "VLC test completed"
        
        if pacman -Q vlc 2>/dev/null; then
          echo "✓ VLC installed"
        else
          echo "⚠ VLC installation skipped or failed"
        fi
      
    - name: Test kubectl installation
      continue-on-error: true
      run: |
        echo "Testing kubectl installation..."
        cd /__w/CachyOS-Setup
        yes n | timeout 120 ./kubectl.fish || echo "kubectl test completed"
        
        # Check if kubectl was installed
        which kubectl && echo "✓ kubectl installed" || echo "⚠ kubectl not found"
      
    - name: Test wrk installation
      continue-on-error: true
      run: |
        echo "Testing wrk installation..."
        cd /__w/CachyOS-Setup
        yes n | timeout 120 ./wrk.fish || echo "wrk test completed"
        
        which wrk && echo "✓ wrk installed" || echo "⚠ wrk not found"
      
    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up test artifacts..."
        # Clean up any temporary files
        rm -rf /tmp/*
        
    - name: Installation Summary
      if: always()
      run: |
        echo "=== Installation Summary ==="
        echo "Available packages:"
        pacman -Q | wc -l
        echo "Installed development tools:"
        which htop nc chromium vlc kubectl wrk 2>/dev/null || echo "Some tools may not be installed"

