name: Test CachyOS Setup Scripts

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      script:
        description: 'Specific script to run (leave empty for all)'
        required: false

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    
    container:
      # Using Arch Linux since CachyOS is Arch-based
      image: archlinux:latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup system
      run: |
        # Update system
        pacman -Syu --noconfirm
        
        # Install essential dependencies
        pacman -S --needed --noconfirm \
          base base-devel \
          fish git curl \
          sudo which \
          openssl
        
        # Configure sudo for GitHub Actions
        echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        useradd -m -G wheel github
      
    - name: Prepare scripts
      run: |
        cd "$GITHUB_WORKSPACE"
        chmod +x *.fish
        echo "📝 Available scripts:"
        ls -1 *.fish
      
    - name: Run specific script
      if: ${{ github.event.inputs.script != '' }}
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "🎯 Running script: ${{ github.event.inputs.script }}"
        
        # Run as non-root user with auto-responses
        runuser -l github -c "cd $GITHUB_WORKSPACE && yes n | ./${{ github.event.inputs.script }}" || echo "⚠ Script execution completed"
      
    - name: Test lint and syntax
      continue-on-error: true
      run: |
        cd "$GITHUB_WORKSPACE"
        
        echo "🔍 Checking Fish syntax..."
        failed=0
        
        for script in *.fish; do
          if fish -n "$script" 2>/dev/null; then
            echo "✅ $script"
          else
            echo "❌ $script - Syntax error"
            failed=1
          fi
        done
        
        if [ $failed -eq 1 ]; then
          echo "⚠ Some scripts have syntax errors"
        fi

